_base_: default.yaml

output_dir: runs/houston

dataset:
  name: houston
  # Houston/
  #   Houston13.mat      + Houston13_7gt.mat   -> source domain
  #   Houston18.mat      + Houston18_7gt.mat   -> target domain
  root: Houston
